### ISSUE TITLE
Default value not returned for client.get

### ISSUE THREAD

**Issue by farridav** [jaysonsantos/django-bmemcached#15]
Im not sure if this is the right place for this issue tbh, as memcache in django involves lots of layers.

Djangos `cache.get` call usually respects default values, `cache.get('non_existent_key', 'default_value')` to give it a dict like experience when using.

Though that doesnt happen with this library, as https://github.com/jaysonsantos/python-binary-memcached/blob/master/bmemcached/client/replicating.py#L51 does not deal with default values in the `get` method.

I am using another very popular library (Django Rest Framework) that is failing because of this, see https://github.com/encode/django-rest-framework/blob/master/rest_framework/throttling.py#L123

As it expects the default value to be returned when the cache key is not present, but it never is.

If this issue has been raised in the wrong place, perhaps you could direct me to the right place ?

Thanks in advance

**Comment by farridav** [comment]
*Bump

**Comment by jaysonsantos** [comment]
Hey there, thanks for your report!
That would be implemented here https://github.com/jaysonsantos/python-binary-memcached/blob/master/bmemcached/client/replicating.py#L30 because `gets` is silent but, it would break its API.
Maybe it would be better to override it here https://github.com/jaysonsantos/django-bmemcached/blob/master/django_bmemcached/memcached.py#L36 as django does with `memcache` library https://github.com/django/django/blob/master/django/core/cache/backends/memcached.py#L178 what do you think?

**Comment by jaysonsantos** [comment]
FYI I've just created a PR here that would solve that problem https://github.com/jaysonsantos/python-binary-memcached/pull/232
